Name:KAUSHAL YADV
CLASS:SY BSC it
ROLL no: 48

Python for Data Structure
Practical No.4


Write a python code to create Numpy Array.

In [23]:
import numpy as np

In [24]:
a = np.array([1,2,3])
print(a)

[1 2 3]


Write a python code to demonstrate basic operations on single array. 


In [25]:
print(a + 3)
print(a * 2)

[4 5 6]
[2 4 6]


Write a python code to create array with 10 elements and slice element from 1st to 5th element.


In [26]:
b = np.array([1,2,3,4,5,6,7,8,9,10])
print(b[0:5])

[1 2 3 4 5]


D.Write a python code to sort an array alphabetically

In [27]:
name = np.array(["kaushal","jay","amit","sunny"])
print(np.sort(name))

['amit' 'jay' 'kaushal' 'sunny']


e.Write a python code to create a filter array that will return maximum values from an array.



In [28]:
price = np.array([300,500,400,600,800])
print(price[price>300])

[500 400 600 800]
